apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app: echo
spec:
  ports:
  - name: echo
    port: 3333
  selector:
    app: echo
  # This line is required for Docker for Mac to expose these ports to your Mac
  type: LoadBalancer
